# Generated by Django 6.0 on 2025-12-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Page Category'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Page name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published',
            field=models.DateField(verbose_name='Page Published Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Post Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Post name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(verbose_name='Post Published Date'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Song Title'),
        ),
    ]
